insert into products (name, description) values ('Denise Cornborough', 'Padded laptop sleeve for protection against scratches.');
insert into products (name, description) values ('Emmanuel Jeffress', 'A meal kit featuring tender chicken with honey sesame sauce.');
insert into products (name, description) values ('Eran Caddy', 'Love-themed molds for creating desserts and treats.');
insert into products (name, description) values ('Madelyn Maleby', 'High-protein pasta made from black beans, gluten-free.');
insert into products (name, description) values ('Daniella Reinger', 'Rich and smooth cold brew coffee concentrate, just add water or milk.');
insert into products (name, description) values ('Jeffie Farrall', 'A seasoning blend of garlic and herbs to enhance any dish.');
insert into products (name, description) values ('Kristal Dowle', 'Crispy sweet potato fries, a delicious side dish.');
insert into products (name, description) values ('Fonsie Hampton', 'Adjustable shelving unit for home or garage storage.');
insert into products (name, description) values ('Farley Bohlin', 'Soft bagels flavored with cinnamon and raisins.');
insert into products (name, description) values ('Kitti Haistwell', 'Engaging kit with science experiments for children.');
insert into products (name, description) values ('Marlee Jery', 'Tangy vinaigrette with orange and ginger flavors.');
insert into products (name, description) values ('Red Kibble', 'Organic rolled oats, great for breakfast or baking.');
insert into products (name, description) values ('Jarrod Gambles', 'Handheld frother for creating frothed milk for coffee.');
insert into products (name, description) values ('Rozanne Sheircliffe', 'Frozen vegetable primavera for quick meals.');
insert into products (name, description) values ('Antoine Eggerton', 'Comprehensive tool set for gardening enthusiasts.');
insert into products (name, description) values ('Link Coker', 'A mix of strawberries, blueberries, and raspberries, perfect for smoothies.');
insert into products (name, description) values ('Benedicta Tynemouth', 'A zesty salsa made with peaches and mangos, great for chips.');
insert into products (name, description) values ('Steward Whiley', 'Fast and convenient air pump for inflating toys and furniture.');
insert into products (name, description) values ('Adina Guittet', 'A mix of fresh raspberries, blueberries, and blackberries.');
insert into products (name, description) values ('Janina Izaks', 'Space-saving bike for indoor workouts.');
insert into products (name, description) values ('Grange Danielovitch', 'Spicy buffalo sauce ideal for wings or dipping.');
insert into products (name, description) values ('Lark Luchetti', 'A retro-style button-down shirt with a relaxed fit.');
insert into products (name, description) values ('Britteny Meneghi', 'Gentle glove for brushing and massaging your pet.');
insert into products (name, description) values ('Carolyne Tytterton', 'Manual blender for smoothies and mixing ingredients on the go.');
insert into products (name, description) values ('Giulietta Garrood', 'A blend of mixed nuts for snacking.');
insert into products (name, description) values ('Glori Kurt', 'Soft cotton graphic tee available in various designs.');
insert into products (name, description) values ('Ashleigh Semper', 'Compact keyboard for tablets and smartphones.');
insert into products (name, description) values ('Abigail Huntingford', 'A flavorful barbecue sauce with a sweet and spicy kick.');
insert into products (name, description) values ('Ursola Mollitt', 'Compact sterilizer for disinfecting small items.');
insert into products (name, description) values ('Latisha Andreasen', 'Complete set for grilling and tailgating fun.');
insert into products (name, description) values ('Daniela Reichelt', 'DIY kit to convert your smartphone into a mini projector.');
insert into products (name, description) values ('Ainslie Hapgood', 'Eco-friendly trash bags that break down naturally.');
insert into products (name, description) values ('Petronella Lenney', 'Pizza topped with barbecue chicken, cheese, and red onions.');
insert into products (name, description) values ('Shirley Kisbey', 'All-natural skincare set for daily use.');
insert into products (name, description) values ('Che Dedon', 'Easy-to-prepare rice with cilantro and lime flavors, great as a side.');
insert into products (name, description) values ('Meier Schoffel', 'Everything you need to build a festive gingerbread house.');
insert into products (name, description) values ('Ferrel De Bernardis', 'Adjustable laptop stand for better ergonomics.');
insert into products (name, description) values ('Jenilee Farny', 'Flexible molds perfect for baking cakes and pastries.');
insert into products (name, description) values ('Ainslee Hixley', 'Juicy burger patties made with grass-fed beef');
insert into products (name, description) values ('Archy Greet', 'A delicious pizza loaded with vegetables');
insert into products (name, description) values ('Chiquita Palethorpe', 'A delightful mix of nuts, fruit, and chocolate.');
insert into products (name, description) values ('Ardine Pedel', 'Bluetooth thermometer that alerts you when your meat is done.');
insert into products (name, description) values ('Diena Pymer', 'A nutritious shake with rich chocolate and refreshing mint flavors.');
insert into products (name, description) values ('Freemon Sibbs', 'Essential tools for bike maintenance and repair.');
insert into products (name, description) values ('Winnifred Meekings', 'Crunchy crackers topped with real cheddar cheese flavor.');
insert into products (name, description) values ('Averil Bethell', 'Unique coffee brewing method for a flavorful experience.');
insert into products (name, description) values ('Faustine Sandilands', 'Make delicious ice cream at home with this user-friendly machine.');
insert into products (name, description) values ('Amalle Stoggell', 'Low-carb pizza crust made from almond flour, gluten-free.');
insert into products (name, description) values ('Lucie Boucher', 'Add a pop of color with this stylish patterned knit scarf.');
insert into products (name, description) values ('Kirbie Blogg', 'Roasted almonds coated in a sweet maple and cinnamon mixture.');
insert into products (name, description) values ('Astra Burberow', 'Sleek and protective sleeve for laptops and tablets.');
insert into products (name, description) values ('Ryun Seiler', 'Spicy cornbread infused with jalapeños for a kick of flavor at your next meal.');
insert into products (name, description) values ('Erick Roddell', 'Comfortable carry for pets while hiking or traveling.');
insert into products (name, description) values ('Renell Enticknap', 'Secure phone mount for your vehicle''s dashboard.');
insert into products (name, description) values ('Reynolds Skellern', 'Set with various resistance bands for workouts.');
insert into products (name, description) values ('Clemence Rolling', 'Warmer for heating baby bottles and food jars.');
insert into products (name, description) values ('Kristi Jan', 'Crunchy granola with almonds and coconut.');
insert into products (name, description) values ('Findley Weavers', 'Gentle brush for removing loose fur from pets.');
insert into products (name, description) values ('Jabez Fleckness', 'Creamy cottage cheese, perfect for healthy snacking.');
insert into products (name, description) values ('Jayme Stirton', 'Classic leather photo album for keepsakes.');
insert into products (name, description) values ('Horst Aksell', 'Personalized nameplate for offices or homes.');
insert into products (name, description) values ('Linnell Faulkes', 'Mix for homemade cornbread, just add water and bake for a delicious side.');
insert into products (name, description) values ('Alexandro Farndell', 'Quick oatmeal with various flavors');
insert into products (name, description) values ('Pru Nowak', 'Adjustable window blinds for privacy and light control.');
insert into products (name, description) values ('Adolf Ewbank', 'Delicious ravioli filled with creamy ricotta and fresh spinach.');
insert into products (name, description) values ('Elfie Wasiela', 'Wearable diffuser for scenting your space and body.');
insert into products (name, description) values ('Lea Havoc', 'Freshly baked whole wheat bread, rich in fiber.');
insert into products (name, description) values ('Tansy Batts', 'Gluten-free bread mix made with almond flour.');
insert into products (name, description) values ('Patrice Beauchop', 'Delicious dark chocolate cups filled with creamy peanut butter.');
insert into products (name, description) values ('Hillier Sykora', 'Smooth and creamy smoothie made with peanut butter and banana.');
insert into products (name, description) values ('Valentijn Devennie', 'Gluten-free flour made from ground chickpeas, great for cooking.');
insert into products (name, description) values ('Shurlock Sonley', 'Fresh organic sweet potatoes, great for roasting or mashing.');
insert into products (name, description) values ('Baily Coxwell', 'Fresh basil pesto, perfect for pasta or as a sandwich spread.');
insert into products (name, description) values ('Ewart Hurn', 'Crunchy granola clusters mixed with nuts and honey.');
insert into products (name, description) values ('Maxine Watson-Brown', 'Concentrated tomato paste, great for sauces.');
insert into products (name, description) values ('Hartwell Godthaab', 'Lightweight fishing rod suitable for beginners.');
insert into products (name, description) values ('Graham Tudor', 'Ergonomic desk that adjusts height for standing or sitting.');
insert into products (name, description) values ('Adoree Dobsons', 'Fresh and crunchy baby carrots ready for snacking.');
insert into products (name, description) values ('Phylys Benda', 'Juicy chicken breast stuffed with spinach and feta cheese, seasoned to perfection.');
insert into products (name, description) values ('Merla Howgill', 'HEPA air purifier for clean indoor air.');
insert into products (name, description) values ('Godfry Giovani', 'Easy-to-heat frozen burritos for a quick meal.');
insert into products (name, description) values ('Durand Derks', 'Soft and strong toilet paper for everyday use.');
insert into products (name, description) values ('Gussy Achurch', 'A trendy oversized denim shirt perfect for layering.');
insert into products (name, description) values ('Eddi Pymer', 'Cold pasta salad tossed with pesto and fresh vegetables.');
insert into products (name, description) values ('Charlena Marner', 'Fresh and organic sweet potatoes, ideal for roasting.');
insert into products (name, description) values ('Dorolisa Dils', 'Creamy chickpea dip, perfect for veggies or pita.');
insert into products (name, description) values ('Sherlocke Posse', 'Compact pocket tool with various built-in functions.');
insert into products (name, description) values ('Bel Nicholson', 'A blend of spices perfect for seasoning steak.');
insert into products (name, description) values ('Hadleigh Pellington', 'A blend of nuts, seeds, and spices for a healthy snack.');
insert into products (name, description) values ('Sybilla Harlock', 'Space-saving shoe organizer for tight spaces.');
insert into products (name, description) values ('Claude McGahey', 'Nutritious protein bars for on-the-go snacking.');
insert into products (name, description) values ('Gwenore Bargery', 'Simple tool to train your pet with positive reinforcement.');
insert into products (name, description) values ('Lilyan Charnock', 'Portable coffee maker for rich brews on the go.');
insert into products (name, description) values ('Gherardo Ollivier', 'Sweet bread with cinnamon and raisins, great for breakfast or snacks.');
insert into products (name, description) values ('Owen Werrett', 'Pancake mix infused with seasonal pumpkin spice flavor.');
insert into products (name, description) values ('Kikelia Deex', 'Elegant chiffon blouse perfect for work or outings.');
insert into products (name, description) values ('Marijn Archer', 'A classic soup combining tomatoes and basil, great with grilled cheese sandwiches.');
insert into products (name, description) values ('Gayleen Glasgow', 'Multi-functional tool for emergency situations in the car.');
insert into products (name, description) values ('Nonnah Yorston', 'Delicious muffins filled with apples and a hint of cinnamon for breakfast.');
insert into products (name, description) values ('Preston Pocke', 'Delicate ravioli filled with roasted butternut squash and spices, perfect with a sage butter sauce.');
