insert into products (name, description) values ('Frozen Chicken Nuggets', 'Crispy chicken nuggets for quick meals.');
insert into products (name, description) values ('Portable Massage Table', 'Folding massage table for professional or home use.');
insert into products (name, description) values ('Sliced Cucumbers', 'Freshly sliced cucumbers, great for salads or snacking.');
insert into products (name, description) values ('Spicy Hummus', 'Creamy hummus with a kick of spice, great for dipping.');
insert into products (name, description) values ('Vegetable Fried Rice Mix', 'A quick and easy fried rice mix with colorful veggies and savory seasoning.');
insert into products (name, description) values ('Zesty Cilantro Lime Dressing', 'A bright and zesty dressing perfect for salads and tacos.');
insert into products (name, description) values ('Honey Garlic Chicken', 'Tender chicken coated in a sweet and savory honey garlic sauce.');
insert into products (name, description) values ('Asian Noodle Salad Kit', 'A pre-packaged salad kit with noodles and Asian-style dressing.');
insert into products (name, description) values ('Chickpea Salad Deluxe', 'Chickpeas mixed with fresh vegetables and herbs, a nutritious snack or salad.');
insert into products (name, description) values ('Sweet Potato and Chickpea Bowl', 'A nourishing bowl of sweet potatoes and chickpeas with spices.');
insert into products (name, description) values ('Plant-Based Protein Bars', 'Nutritious protein bars for on-the-go snacking.');
insert into products (name, description) values ('Luxury Bath Salts', 'Scented bath salts for relaxation and self-care.');
insert into products (name, description) values ('Wireless Earbuds', 'True wireless earbuds with touch control.');
insert into products (name, description) values ('Magnetic Puzzle Board', 'Magnetic puzzle assembly board for kids.');
insert into products (name, description) values ('Red Lentil Pasta', 'Gluten-free pasta made from red lentils, packed with protein.');
insert into products (name, description) values ('Pet Grooming Glove', 'Gentle glove for brushing and massaging your pet.');
insert into products (name, description) values ('Couscous Mix', 'Fluffy couscous that cooks in just minutes, perfect as a side.');
insert into products (name, description) values ('Chocolate Avocado Pudding', 'Rich and creamy pudding made with ripe avocados and cocoa.');
insert into products (name, description) values ('Weighted Blanket for Adults', 'A calming blanket that provides gentle pressure for relaxation.');
insert into products (name, description) values ('Wall-Mounted Wine Rack', 'Stylish and modern holder for storing wine bottles on walls.');
insert into products (name, description) values ('Winter Insulated Jacket', 'Warm and stylish jacket for cold weather.');
insert into products (name, description) values ('DIY Lip Balm Kit', 'Craft your own lip balms with this complete kit.');
insert into products (name, description) values ('Luxury Memory Foam Mattress Topper', 'Adds extra comfort to your mattress for a better night''s sleep.');
insert into products (name, description) values ('Desk Organizer Set', 'Stylish desk set to keep your workspace tidy and organized.');
insert into products (name, description) values ('Insulated Coffee Mug', 'Double-walled mug to keep your drink hot for longer.');
insert into products (name, description) values ('High-Quality Yoga Mat', 'Non-slip mat designed for yoga and fitness exercises.');
insert into products (name, description) values ('Cacao Powder', 'Unsweetened cacao powder for baking and smoothies.');
insert into products (name, description) values ('Handmade Leather Wallet', 'High-quality leather wallet with multiple compartments.');
insert into products (name, description) values ('Golf Putting Green', 'Indoor putting green for practicing your putting skills.');
insert into products (name, description) values ('Adjustable Stand for Tablets and Smartphones', 'Multi-angle stand for easy viewing of devices.');
insert into products (name, description) values ('Maxi Wrap Dress', 'A flowy maxi dress perfect for both casual and semi-formal occasions.');
insert into products (name, description) values ('Sweet Potato Mash', 'Creamy mashed sweet potatoes, ready to heat and serve.');
insert into products (name, description) values ('Chili Beans in Sauce', 'Canned beans cooked in a savory chili sauce');
insert into products (name, description) values ('Solar Charger', 'Portable solar charger for outdoor adventures.');
insert into products (name, description) values ('Granola Clusters', 'Crunchy granola clusters, perfect for snacking or topping yogurt.');
insert into products (name, description) values ('Smart Thermostat with Wi-Fi', 'Wi-Fi enabled thermostat that learns your habits.');
insert into products (name, description) values ('Maple Syrup', 'Pure maple syrup for pancakes and more.');
insert into products (name, description) values ('Portable Solar Camp Shower', 'Portable solar shower for camping and outdoor use.');
insert into products (name, description) values ('Dog Training Clicker', 'Training tool for reinforcing commands and behavior in dogs.');
insert into products (name, description) values ('Chocolate Coconut Protein Balls', 'No-bake protein balls with chocolate and coconut flavors.');
insert into products (name, description) values ('Dog Training Collar', 'Rechargeable training collar for effective behavior training.');
insert into products (name, description) values ('Halloween Decoration Set', 'Fun decorations for Halloween to set a spooky atmosphere.');
insert into products (name, description) values ('LED Christmas Tree Lights', 'String lights for decorating holiday trees.');
insert into products (name, description) values ('Electric Stool Heater', 'Heated stool cover for extra comfort during winter.');
insert into products (name, description) values ('Pineapple Rings', 'Delicious canned pineapple rings for desserts or salads.');
insert into products (name, description) values ('Smartphone Gimbal Stabilizer', 'Stabilizer for smooth video recording with smartphones.');
insert into products (name, description) values ('Spicy BBQ Sauce', 'A tangy and spicy BBQ sauce that''s perfect for grilling.');
insert into products (name, description) values ('Peanut Butter Pretzel Nuggets', 'Crunchy pretzel nuggets filled with creamy peanut butter.');
insert into products (name, description) values ('Biodegradable Phone Case', 'Eco-friendly phone case designed to decompose safely.');
insert into products (name, description) values ('Vanilla Pudding Mix', 'Instant mix for creamy vanilla pudding.');
insert into products (name, description) values ('Honey Ginger Tea', 'Soothing tea with honey and ginger, great for relaxation.');
insert into products (name, description) values ('Wall-Mounted Wine Rack', 'Stylish and modern holder for storing wine bottles on walls.');
insert into products (name, description) values ('Kombucha Drink', 'Refreshing and tangy fermented tea, available in various flavors.');
insert into products (name, description) values ('Frozen Hash Browns', 'Shredded potatoes, perfect for breakfasts.');
insert into products (name, description) values ('Sour Cream', 'Tangy sour cream, perfect for dips and toppings.');
insert into products (name, description) values ('Pepper Jack Cheese Slices', 'Creamy cheese with a spicy kick, perfect for sandwiches.');
insert into products (name, description) values ('Chili Powder', 'Spicy chili powder to add heat to dishes.');
insert into products (name, description) values ('Rechargeable Electric Screwdriver', 'Convenient electric screwdriver for DIY projects at home.');
insert into products (name, description) values ('Granulated Sugar', 'Fine granulated sugar for all your baking needs.');
insert into products (name, description) values ('Halloween Decoration Set', 'Fun decorations for Halloween to set a spooky atmosphere.');
insert into products (name, description) values ('Italian Herb Balsamic Marinade', 'A rich marinade perfect for meats and vegetables, infused with Italian herbs and balsamic vinegar.');
insert into products (name, description) values ('Lemon Herb Quinoa', 'Fluffy quinoa mixed with lemon zest and herbs, a perfect side.');
insert into products (name, description) values ('Window Blinds', 'Adjustable window blinds for privacy and light control.');
insert into products (name, description) values ('Personalized Pet ID Tags', 'Custom engraved ID tags for pets with your contact information.');
insert into products (name, description) values ('Ready-to-Eat Chili', 'Spicy chili in a can, ready to eat for a filling meal.');
insert into products (name, description) values ('Italian Herb Balsamic Marinade', 'A rich marinade perfect for meats and vegetables, infused with Italian herbs and balsamic vinegar.');
insert into products (name, description) values ('Adjustable Kitchen Broom Stand', 'Space-saving broom holder for organized cleaning supplies.');
insert into products (name, description) values ('Canvas Tote Bag', 'Durable canvas tote bag, perfect for everyday use.');
insert into products (name, description) values ('Personal Safety Alarm', 'Compact alarm for personal safety and security.');
insert into products (name, description) values ('Lemon Dill Salmon', 'Salmon fillets seasoned with lemon and dill, perfect for grilling.');
insert into products (name, description) values ('Baked Mac and Cheese', 'Creamy macaroni and cheese baked to perfection.');
insert into products (name, description) values ('Peanut Butter Granola', 'Crunchy granola full of peanut butter flavor and oats.');
insert into products (name, description) values ('Quinoa & Black Bean Salad', 'A nutritious salad with quinoa and black beans');
insert into products (name, description) values ('Bamboo Charcoal Air Purifier Bags', 'Natural air purifiers to absorb odors and moisture.');
insert into products (name, description) values ('Whole Grain Hamburger Buns', 'Soft hamburger buns made with whole grains.');
insert into products (name, description) values ('Electric Kettle with Temperature Control', 'Electric kettle that offers precise temperature settings.');
insert into products (name, description) values ('Pleated Midi Dress', 'A stylish midi dress with stylish pleats, suitable for any occasion.');
insert into products (name, description) values ('Customizable Photo Calendar', 'Personalized calendar with your favorite photos.');
insert into products (name, description) values ('Pasta Maker', 'Manual pasta maker for homemade pasta.');
insert into products (name, description) values ('Chicken Sausage', 'Flavorful chicken sausage, low in fat and fully cooked.');
insert into products (name, description) values ('Customizable Name Puzzle', 'Personalized wooden puzzles for children that encourage learning.');
insert into products (name, description) values ('Multi-Purpose Scissors', 'Heavy-duty scissors for crafting and office use.');
insert into products (name, description) values ('Smart LED Light Strip', 'Customizable RGB LED light strip, perfect for mood lighting.');
insert into products (name, description) values ('Organic Brown Sugar', 'Natural sweetener for baking and cooking.');
insert into products (name, description) values ('Interactive Robot Toy', 'Fun robot that engages kids with games and activities.');
insert into products (name, description) values ('Chocolate Avocado Pudding', 'Rich and creamy pudding made with ripe avocados and cocoa.');
insert into products (name, description) values ('Stainless Steel Mixing Bowls', 'Set of versatile mixing bowls for cooking.');
insert into products (name, description) values ('Athletic Sports Bra', 'Supportive sports bra designed for high-impact workouts, made with moisture-wicking fabric.');
insert into products (name, description) values ('Cinnamon Ice Cream', 'Creamy ice cream with a warm cinnamon flavor, perfect for dessert.');
insert into products (name, description) values ('Cheesy Cauliflower Bake', 'A frozen cheesy bake made with cauliflower, great as a side dish or a vegetarian meal.');
insert into products (name, description) values ('Repair Tool Set for Home Improvement', 'Small toolkit with essentials for home repairs.');
insert into products (name, description) values ('Coffee Grinder', 'Burr coffee grinder for fresh ground coffee.');
insert into products (name, description) values ('Marinated Artichokes', 'Artichoke hearts marinated in herbs and oil.');
insert into products (name, description) values ('Energy Protein Bars', 'Nutritious bars packed with protein for energy');
insert into products (name, description) values ('Smart Thermostat with Wi-Fi', 'Wi-Fi enabled thermostat that learns your habits.');
insert into products (name, description) values ('Sweet Cherry Tomatoes', 'Fresh and juicy cherry tomatoes for salads and snacking.');
insert into products (name, description) values ('Honeycrisp Apple Chips', 'Crispy and sweet dried apple slices');
insert into products (name, description) values ('Wireless Charger Stand', 'Convenient charging stand for smartphones and devices.');
insert into products (name, description) values ('Dish Soap Dispenser', 'Stylish dish soap dispenser with sponge holder.');
insert into products (name, description) values ('Fall-Themed Table Runner', 'Decorative table runner perfect for autumn gatherings.');
